name: "Install visionOS Runtime"
description: "Install visionOS Runtime"
inputs:
  developer_dir:
    description: "Xcode developer directory"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Install visionOS Runtime"
      shell: bash
      run: |
        sudo xcode-select -s ${{ inputs.developer_dir }}
        sudo xcodebuild -runFirstLaunch
        sudo xcrun simctl list
        sudo xcodebuild -downloadPlatform visionOS
        sudo xcodebuild -runFirstLaunch
