name: "Download and unpack xcarchive"
description: "Download and unpack xcarchive"
inputs:
  platform:
    description: "Platform to download and unpack"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download ${{ inputs.platform }} Framework
      uses: actions/download-artifact@v4
      with:
        name: xcarchive-${{ inputs.platform }}
        path: ./builder/build

    - name: Unpack ${{ inputs.platform }} Framework
      shell: bash
      working-directory: ./builder/build
      run: |
        unzip ${{ inputs.platform }}.xcarchive.zip
        rm ${{ inputs.platform }}.xcarchive.zip

        ls -la
        ls -la ${{ inputs.platform }}.xcarchive
