name: CI

# Controls when the workflow will run
on:
  push:
    branches: [test-ci]
    # paths:
    #   - "td" # on TDLib updates

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  TDLIB_REPO: https://github.com/tdlib/td
  ARTIFACT_NAME: TDLibFramework.zip
  ARTIFACT_DIR: ./builder/build

jobs:
  # Tests
  tests:
    runs-on: macos-latest
    needs: [merge-xcframework]
    strategy:
      matrix:
        platform: ["macOS"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upload Project
        uses: actions/upload-artifact@v2
        with:
          name: project-${{ matrix.platform }}.zip
          path: project-${{ matrix.platform }}.zip
          if-no-files-found: error

      - name: Run Tests for ${{ matrix.platform }}
        run: ./scripts/test.sh ${{ matrix.platform }}